---
- block:

  - name: 'Install /etc/pacman.d/null.conf'
    copy:
      src: 'etc_pacman.d/null.conf'
      dest: /etc/pacman.d/

  # Routers shouldn't be consuming AUR packages.
  #
  # Webservers host custom repositories, and already have /etc/pacman.d/*.conf
  # files defining how to access said custom repositories.
  - name: Install /etc/pacman.d/ichi-public.conf
    copy:
      src: etc_pacman.d/ichi-public.conf
      dest: /etc/pacman.d/
    notify: Sync ichi-public repository
    when:
      - '"routers" not in group_names'
      - '"webservers" not in group_names'

  - name: Install /etc/pacman.d/ichi-private.netrc
    template:
      src: ichi-private.netrc
      dest: /etc/pacman.d/
    when:
      - '"workstations" in group_names'
      - '"ichi-private" in pacman_conf_repo_passwords'

  - name: Install /etc/pacman.d/ichi-private.conf
    copy:
      src: etc_pacman.d/ichi-private.conf
      dest: /etc/pacman.d/
    notify: Sync ichi-private repository
    when: '"workstations" in group_names'

  - name: Install /etc/pacman.conf
    template:
      src: pacman.conf
      dest: /etc/pacman.conf
    notify: Sync all repositories

  - name: Install reflector
    pacman:
      name: reflector

  # Try executing `systemctl list-unit-files | grep update`. You'll find that
  # units named verb-noun are atypical, and units named noun-verb are typical.
  - name: Delete old mirrorlist units
    file:
      path: /etc/systemd/system/update-mirrorlist.{{ item }}
      state: absent
    loop:
      - timer
      - service
    register: result

  - name: Reload systemd
    systemd:
      daemon_reload: true
    when: result is changed

  - name: Install units to update the mirrorlist
    copy:
      src: etc_systemd_system/
      dest: /etc/systemd/system/

  - name: Start and enable timer to update the mirrorlist
    systemd:
      name: mirrorlist-update.timer
      state: started
      enabled: true
      daemon_reload: true

  - name: Install pacman-contrib (for paccache)
    pacman:
      name: pacman-contrib

  - name: Start and enable timer to clean the package cache
    systemd:
      name: paccache.timer
      state: started
      enabled: true
      daemon_reload: true

  become: true
